name: Build and Push Docker Image with Kaniko to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - '**/*.dockerfile'

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image with Kaniko
        uses: aevea/kaniko-action@v0.8.0
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
          dockerfile: ./Dockerfile
          context: .

      - name: Verify Image Push
        run: echo "Docker image pushed successfully to Docker Hub"
