name: Build and Push Docker Image with Kaniko

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image with Kaniko
        run: |
          docker run \
            --rm \
            -v $(pwd):/workspace \
            -v $HOME/.docker:/kaniko/.docker \
            gcr.io/kaniko-project/executor:latest \
            --dockerfile /workspace/Dockerfile \
            --destination=${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} \
            --context=dir:///workspace \
            --cache=true \
            --cache-repo=${{ secrets.DOCKER_USERNAME }}/kaniko-cache:latest
